name: Demo builds
on:
  push:
  workflow_dispatch:

jobs:
  no-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: carbon-app/carbon
          path: carbon

      - run: |
          cp Dockerfile .dockerignore carbon

      - uses: docker/setup-buildx-action@v2
        with:
          # We're using an experimental version of buildx for s3 support
          driver-opts: image=moby/buildkit:master

      - uses: docker/build-push-action@v3
        with:
          tags: carbon:latest
          load: true
          file: Dockerfile
          context: carbon
